### ISSUE TITLE
Does wire gauge matter?

### ISSUE THREAD

**Issue by Trevo525** [hanneslinder/retro-speaker#1]
I am testing an AMP with just a DAC and Aux cord connected to my phone using speakers I bought on Aliexpress and the sound quality was pretty bad. I wasn't expecting much, but I bought two different ones to try and pick the best and I am wondering if I should invest in some lower gauge wire for these speakers. I am using some stranded 22 Gauge that I already had for some projects. Could that be an issue? How do you know what gauge wire you should use in a project like this?

Thanks for your help!

**Comment by hanneslinder** [comment]
Sorry for the late reply!
I don't think wire gauge should matter too much, but from my testing I found that the quality of AliExpress bluetooth DACs varies quite a lot. My first two modules had really bad audio quality and lots of static noise, while the one I am using now (https://de.aliexpress.com/item/1005006744130939.html?spm=a2g0o.productlist.main.25.62a7f91ff8XP5L&algo_pvid=d2526900-fd57-49c5-9613-ecc1059de114&utparam-url=scene%3Asearch%7Cquery_from%3A) sounds really good.
